### PR TITLE
Add telepoison

### PR DESCRIPTION
**Pull request by cpiemontese**

### CODE REVIEW

**Comment by tsloughter** [comment]
Can you rename the application and directory to match the others, `opentelemetry_httpoison`

**Comment by cpiemontese** [comment]
It took TOO long, but I finally managed to get the CLA signed :tada:

**Comment by tsloughter** [comment]
Great!

Can you change the name of the `telepoison.ex` module to `opentelemetry_httpoison`?

**Comment by cpiemontese** [comment]
Renamed everything. In the meantime we actually had [a bunch of changes](https://github.com/primait/telepoison/releases) (none of them breaking), shall I try to align this PR with the latest version...?

**Comment by tsloughter** [comment]
@cpiemontese that'd be great, yea

**Comment by tsloughter** [comment]
Hey, sorry, I forgot you'll also need to add an entry for it to https://github.com/open-telemetry/opentelemetry-erlang-contrib/blob/main/.github/workflows/elixir.yml so tests get run.

**Review by tsloughter — APPROVED** [review]

**Comment by tsloughter** [comment]
I'm going to merge this but if you want to be an approver on changes to it (I'd like it if you were and were interested in doing so) you'll need to send another PR with an update to the top level CODEOWNERS file.

**Pull request merged**
