### PR TITLE
adding opentelemetry_plug

### PR DESCRIPTION
**Pull request by jaycee999**
Essentially [this repo](https://github.com/opentelemetry-beam/opentelemetry_plug) updated to use OTel 1.0

In an [Elixir slack convo in #opentelemetry ](https://elixir-lang.slack.com/archives/CA4CNK38B/p1687793763537299?thread_ts=1687792729.112349&cid=CA4CNK38B)it was discovered that the above linked repo wasn't ever migrated to this one; nor published to hex as a package.

### CODE REVIEW

**Comment by tsloughter** [comment]
Thanks! Since this is just a copy over of the existing lib I guess we could merge this but technically it needs updating to use the latest semantic conventions application for attribute keys. Would you be interested in doing that in this PR (I can give more details if so) or should we just merge this and then worry about someone doing the updates?

**Comment by jaycee999** [comment]
I can look into that. And sorry I'm a late on the CLA.  I'm not sure what the stance is on how the company I'm with wants to handle that part of things and I hope to get it sorted soon.

**Comment by jaycee999** [comment]
> Thanks! Since this is just a copy over of the existing lib I guess we could merge this but technically it needs updating to use the latest semantic conventions application for attribute keys. Would you be interested in doing that in this PR (I can give more details if so) or should we just merge this and then worry about someone doing the updates?

@tsloughter Does the latest commit address things correctly?

**Comment by tsloughter** [comment]
@jaycee999 hey, sorry, why was this closed? I don't recall if the CLA was signed or not.

**Comment by jaycee999** [comment]
@tsloughter I just haven't been able to get any momentum on getting the CLA signed and don't know how long it's going to take to get answers.  It also doesn't seem to be an instrument too many people are concerned with so I figured maybe I ought to close this.  I'm happy to reopen but I still have to get my employer to sign off.  lmk

**Pull request closed without merging**
