### PR TITLE
Add tests to cover new liveview integration

### PR DESCRIPTION
**Pull request by derekkraan**
Following up on #198.

### CODE REVIEW

**Review by tsloughter — APPROVED** [review]
Thanks! I would like @bryannaegele to take a look before its merged, but I'm approving.

**Comment by derekkraan** [comment]
Is there a reason that all the tests in the matrix are being skipped?

**Comment by bryannaegele** [comment]
> Is there a reason that all the tests in the matrix are being skipped?

Forks can't trigger test runs without a maintainer giving it the initial trigger, I think. There's something there about that.

Given the number of tests we have and that the runners are shared with all of otel, I'm inclined to not change the behavior.

**Comment by derekkraan** [comment]
Fixed the tests. Not sure why `mix format` ran with another version of Elixir when I submitted initially. This PR is ready for another look.

**Review by bryannaegele — APPROVED** [review]

**Pull request merged**
