### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by bryannaegele**
I'm gonna regret this but it's also the only way to stay on top of this for new releases.

### CODE REVIEW

**Comment by tsloughter** [comment]
This is good but https://github.com/renovatebot/renovate does support Elixir and may be a better option.

**Review by tsloughter — APPROVED** [review]

**Comment by bryannaegele** [comment]
Oh. It does show up when you search. I initially ruled it out because neither language was listed in "Language Support". I'll check it out

**Comment by bryannaegele** [comment]
Ok. I'll look into renovate more since it appears we can do a custom manager to handle erlang

**Comment by bryannaegele** [comment]
I'm going to close this in favor of getting renovate set up.

**Pull request closed without merging**
