### PR TITLE
Optionally disable trace propagation for Tesla

### PR DESCRIPTION
**Pull request by andrewhr**
While we always want spans being produced, trace progation is not desirable in all cases - namely, when calling external parties, as that may leak sensitive information, like one present on Baggage.

This patch introduces a new option `:propagate`, that defaults to `true`.

Some tweaks are made to existing propagation test, fixing how options are used. The approach here is closer to what we see in some middleware tests of Tesla itself.

### CODE REVIEW

**Comment by bryannaegele** [comment]
Would you not just have different clients per destination or not include the middleware if not using macros?

**Comment by tsloughter** [comment]
Those options wouldn't resolve the fact that you should be able to use any propagator,not just he global default. Not sure that is defined in the spec yet or not, but its what should be available.

**Comment by andrewhr** [comment]
> Instead I think it should be a propagator option that can override the default global propagator which can then be set to none or undefined to disable propagation.

I didn't considered that approach because... I didn't know was a thing! How that would look like (in pseudo-code)? Those overrides will work per Tesla client? I want *some* requests to propagate and other requests to not propagate, but both should produce traces/metrics etc.

> Would you not just have different clients per destination or not include the middleware if not using macros?

Not sure if I follow. The idea is, I want spans, I just not want to propagate. I need the middleware for that (on current version)

**Comment by tsloughter** [comment]
@andrewhr it would work the same way but set `propagator: none` as the option instead of `propagate: true`.

**Comment by tsloughter** [comment]
Yes, I think override in opts is the way to go. I don't think there should be any needed SDK work for this.

**Comment by tsloughter** [comment]
@andrewhr do you think you'll get to this soon or should I try to take a crack at it?

**Comment by tsloughter** [comment]
I think this is closed by https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/146/files

**Pull request closed without merging**
