### PR TITLE
Add bandit telemetry support for opentelemetry-phoenix

### PR DESCRIPTION
**Pull request by solar05**
## New Project

Telemetry handler that creates Opentelemetry spans from [Bandit events](https://hexdocs.pm/bandit/Bandit.Telemetry.html#content).
[Project link.](https://github.com/samokat-oss/opentelemetry-bandit)

### Checklist

**Acknowledgements**

- [x] I certify that I am authorized to assign ownership of this code to the OpenTelemetry project.
- [x] I acknowledge that ownership of the [Hex](https://hex.pm) package must be given/transferred to the [OpenTelemetry Hex Org](https://hex.pm/orgs/opentelemetry)

**Project Type**

- [x] Instrumentation
- [ ] Exporter
- [ ] Propagator
- [ ] Metapackage
- [ ] Example
- [ ] Util

**Prior Art**

- [ ] Is this an existing project? Includes private libraries being open sourced.
  - [x] Yes
  - [ ] No
- [ ] Are there any other packages on [Hex](https://hex.pm) providing similar functionality?
  
**Existing Project**

- [x] Moving from an existing public repository? Provide a link in the description.
- [x] All authors who have contributed code contained in this PR have signed the [CNCF CLA](https://identity.linuxfoundation.org/projects/cncf)

**All Projects**

- [x] Label created (maintainers)
- [x] [labeler.yml](https://github.com/open-telemetry/opentelemetry-erlang-contrib/blob/main/.github/labeler.yml) updated
- [x] CI
  - [x] Elixir or Erlang language file is updated
  - [x] Test strategy should use the matrix strategy with all supported language/OTP combinations
  - [x] The job is scoped to only run for relevant code changes
- [x] [Codeowners](https://github.com/open-telemetry/opentelemetry-erlang-contrib/blob/main/CODEOWNERS) adds scoped ownership for project maintainers
- [x] License file (Apache2 - copyright to OpenTelemetry Authors)
- [x] All code complies with the [Otel Specification](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification) and Otel Semantic Conventions - [Trace](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/trace/semantic_conventions) [Metrics](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions)

### CODE REVIEW

**Comment by bryannaegele** [comment]
This is awesome. Will take a look after the new year

**Comment by bryannaegele** [comment]
@solar05 ping.

Simplebet will be able to invest time building the library out if we can get the transfer completed. We'd prefer to not have a second version in the ecosystem if at all possible.

**Comment by solar05** [comment]
@bryannaegele oh, sorry, got busy days! Moved core project. What kind of ownership is meant? Hexpm?

**Comment by bryannaegele** [comment]
Awesome! Here's a PR template https://github.com/open-telemetry/opentelemetry-erlang-contrib/blob/main/.github/PULL_REQUEST_TEMPLATE/new_project_template.md for transferring. And yeah, the package transfer would be ownership to the org.

**Comment by solar05** [comment]
@bryannaegele update PR description according to the new project template, also transferred package ownership to opentelemetry.

**Comment by bryannaegele** [comment]
Thank you! I'll try to get this merged this week.

**Review by bryannaegele — APPROVED** [review]

**Comment by ianko** [comment]
@bryannaegele Is there a release planned for `opentelemetry_phoenix` to include the `:bandit` adapter to `OpentelemetryPhoenix.setup/1`?

**Comment by akasprzok** [comment]
> @ianko we need a change in bandit and some refactoring to sign off on making it an option as it currently degrades the default behavior of the phoenix instrumenter. Once that all happens, we can expose it as an option.

Seconding @barkerja - is there somewhere we can follow this? Would be extremely timely and useful for us.

**Pull request merged**
