### PR TITLE
chore(broadway): update opentelemetry_semantic_attributes to SemConv 1.27

### PR DESCRIPTION
**Pull request by klacointe**

### CODE REVIEW

**Comment by klacointe** [comment]
up ?

**Comment by lud-wj** [comment]
+1 for this pr, this prevent us to upgrade our OTEL dependencies.

**Comment by bryannaegele** [comment]
@klacointe can you please confirm you have thoroughly reviewed the [Messaging Specification](https://hexdocs.pm/opentelemetry_semantic_conventions/messaging.html) for any new or changed attributes that are applicable? As far as I can tell this was not performed since nothing has changed in the setup for opting into experimental attirbutes which is essentially the entire messaging specification. Please refer to bandit, phoenix, cowboy, etc to familiarize yourself with the expected API.

Thanks

**Comment by danschultzer** [comment]
FWIW I've updated the attributes and span names to the 1.27 guidelines for oban: https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/436

Among other things the span name must be updated, and there's also a whole thing on creation context.

**Comment by klacointe** [comment]
Closing in favor of #435 and #436

**Pull request closed without merging**
