### PR TITLE
Relax dependencies for opentelemtry_tesla

### PR DESCRIPTION
**Pull request by dvic**

### CODE REVIEW

**Comment by dvic** [comment]
There was also a typo in `mix.exs`, no idea how the CI passed with this typo?

**Review by bryannaegele — APPROVED** [review]
CI was broken so it probably didn't pick it up

**Comment by dvic** [comment]
Did the CI now run at all? I don't see the job, it looks like it was skipped:

image

**Comment by andrewhr** [comment]
Can we release a new version of `opentelemetry_tesla` with this change?

**Comment by gerbal** [comment]
Any chance of cutting a `2.0.2` release with this change?

**Comment by dvic** [comment]
> Did the CI now run at all? I don't see the job, it looks like it was skipped:
> 
> image

@bryannaegele ping, I'm not sure the CI is currently set up correctly :)

**Comment by ricardoccpaiva** [comment]
@gerbal @andrewhr I believe this answers your questions 👇 
https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/112

Once it's merged I'll deploy a new version of the package.

**Pull request merged**
