### PR TITLE
Bump opentelemetry_tesla version

### PR DESCRIPTION
**Pull request by ricardoccpaiva**
Bump version from `2.0.1` to `2.10` as there were some minor changes in the past few weeks.

- https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/106/
- https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/105

### CODE REVIEW

**Review by tsloughter — APPROVED** [review]

**Comment by ricardoccpaiva** [comment]
actually I don't haver permissions to merge 😅

**Comment by ricardoccpaiva** [comment]
Can't 😢 
image

**Comment by bryannaegele** [comment]
@ricardoccpaiva what's your hex username again?

**Comment by bryannaegele** [comment]
@ricardoccpaiva try it again. I added you as a maintainer. Hopefully that gets the permissions right now.

**Comment by tsloughter** [comment]
Oh, yea, I guess they arenj't.

**Pull request merged**
